/**
 * ANKANITOR KNOWLEDGE BASE — DEFINITIVE REGIONAL DATA MATRIX
 * All 28 States + 8 Union Territories
 *
 * Core attributes (from canonical matrix):
 *  - is_state, region, has_coastline, highly_mountainous, shares_international_border
 *  - dominant_language_family, high_literacy_85_plus, major_cultural_identifier
 *
 * Extended deduction attributes:
 *  - historic_portuguese_influence, historic_french_influence, famous_for_deserts
 *  - is_in_northeast, population_large, area_large, formed_after_2000
 *  - is_island_territory, hindi_speaking_majority, known_for_tea_coffee
 *  - known_for_beaches, known_for_spices, known_for_it_industry
 *  - has_significant_tribal_population, borders_pakistan, borders_china
 *  - borders_bangladesh, borders_nepal, borders_myanmar
 *  - known_for_historical_monuments, has_backwaters_or_lagoons
 *  - known_for_wildlife_sanctuaries, capital_is_major_metro, smallest_by_area
 */

const ANKANITOR_KNOWLEDGE_BASE = [
  // ═══════════════════════════════════════
  //  STATES (28)
  // ═══════════════════════════════════════

  {
    name: "Andhra Pradesh",
    is_state: true,
    region: "South",
    has_coastline: true,
    highly_mountainous: false,
    shares_international_border: false,
    dominant_language_family: "Dravidian",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Tirupati, Kuchipudi, Tech Hubs",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: true,
    area_large: true,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: true,
    known_for_it_industry: false,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: true
  },
  {
    name: "Arunachal Pradesh",
    is_state: true,
    region: "East",
    has_coastline: false,
    highly_mountainous: true,
    shares_international_border: true,
    dominant_language_family: "Sino-Tibetan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Tawang Monastery, Dawn-lit Mountains",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: true,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: false,
    borders_china: true,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: true,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Assam",
    is_state: true,
    region: "East",
    has_coastline: false,
    highly_mountainous: false,
    shares_international_border: true,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Bihu, Tea Gardens, One-horned Rhino",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: true,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: true,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: true,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: true
  },
  {
    name: "Bihar",
    is_state: true,
    region: "East",
    has_coastline: false,
    highly_mountainous: false,
    shares_international_border: true,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Nalanda, Mahabodhi Temple, Chhath Puja",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: true,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: true,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: true,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Chhattisgarh",
    is_state: true,
    region: "Central",
    has_coastline: false,
    highly_mountainous: false,
    shares_international_border: false,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Tribal Culture, Chitrakote Falls, Minerals",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: true,
    formed_after_2000: true,
    is_island_territory: false,
    hindi_speaking_majority: true,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Goa",
    is_state: true,
    region: "West",
    has_coastline: true,
    highly_mountainous: false,
    shares_international_border: false,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: true,
    major_cultural_identifier: "Beaches, Portuguese Heritage, Cashews",
    historic_portuguese_influence: true,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: true,
    known_for_spices: true,
    known_for_it_industry: false,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: false,
    smallest_by_area: true,
    known_for_classical_dance: false
  },
  {
    name: "Gujarat",
    is_state: true,
    region: "West",
    has_coastline: true,
    highly_mountainous: false,
    shares_international_border: true,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Garba, Gir Lions, Statue of Unity, Business",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: true,
    is_in_northeast: false,
    population_large: true,
    area_large: true,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: true,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Haryana",
    is_state: true,
    region: "North",
    has_coastline: false,
    highly_mountainous: false,
    shares_international_border: false,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Sports/Olympians, Agriculture, Mahabharata",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: true,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: true,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Himachal Pradesh",
    is_state: true,
    region: "North",
    has_coastline: false,
    highly_mountainous: true,
    shares_international_border: true,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: true,
    major_cultural_identifier: "Himalayas, Apples, Hill Stations",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: true,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: true,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Jharkhand",
    is_state: true,
    region: "East",
    has_coastline: false,
    highly_mountainous: false,
    shares_international_border: false,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Dhoni, Coal Mines, Baidyanath Temple",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: false,
    formed_after_2000: true,
    is_island_territory: false,
    hindi_speaking_majority: true,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Karnataka",
    is_state: true,
    region: "South",
    has_coastline: true,
    highly_mountainous: true,
    shares_international_border: false,
    dominant_language_family: "Dravidian",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Bengaluru IT, Mysore Palace, Hampi",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: true,
    area_large: true,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: true,
    known_for_beaches: false,
    known_for_spices: true,
    known_for_it_industry: true,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: true,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Kerala",
    is_state: true,
    region: "South",
    has_coastline: true,
    highly_mountainous: true,
    shares_international_border: false,
    dominant_language_family: "Dravidian",
    high_literacy_85_plus: true,
    major_cultural_identifier: "Backwaters, Ayurveda, Houseboats, Kathakali",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: true,
    known_for_beaches: true,
    known_for_spices: true,
    known_for_it_industry: false,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: true,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: true
  },
  {
    name: "Madhya Pradesh",
    is_state: true,
    region: "Central",
    has_coastline: false,
    highly_mountainous: false,
    shares_international_border: false,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Khajuraho, Tigers, Indore Cleanliness",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: true,
    area_large: true,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: true,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Maharashtra",
    is_state: true,
    region: "West",
    has_coastline: true,
    highly_mountainous: true,
    shares_international_border: false,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Bollywood, Shivaji, Vada Pav, Ganpati",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: true,
    area_large: true,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: true,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: true,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Manipur",
    is_state: true,
    region: "East",
    has_coastline: false,
    highly_mountainous: true,
    shares_international_border: true,
    dominant_language_family: "Sino-Tibetan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Loktak Lake, Classical Dance, Sangai Deer",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: true,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: true,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: true
  },
  {
    name: "Meghalaya",
    is_state: true,
    region: "East",
    has_coastline: false,
    highly_mountainous: true,
    shares_international_border: true,
    dominant_language_family: "Austroasiatic",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Living Root Bridges, Clouds, Cleanest Village",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: true,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: true,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Mizoram",
    is_state: true,
    region: "East",
    has_coastline: false,
    highly_mountainous: true,
    shares_international_border: true,
    dominant_language_family: "Sino-Tibetan",
    high_literacy_85_plus: true,
    major_cultural_identifier: "Bamboo Dance, High Hills, Mizo Hills",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: true,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: true,
    borders_nepal: false,
    borders_myanmar: true,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Nagaland",
    is_state: true,
    region: "East",
    has_coastline: false,
    highly_mountainous: true,
    shares_international_border: true,
    dominant_language_family: "Sino-Tibetan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Hornbill Festival, Naga Tribes",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: true,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: true,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Odisha",
    is_state: true,
    region: "East",
    has_coastline: true,
    highly_mountainous: false,
    shares_international_border: false,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Jagannath Puri, Konark Sun Temple, Odissi",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: true,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: true,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: true
  },
  {
    name: "Punjab",
    is_state: true,
    region: "North",
    has_coastline: false,
    highly_mountainous: false,
    shares_international_border: true,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Golden Temple, Bhangra, Lassi, Wagah Border",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: false,
    borders_pakistan: true,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Rajasthan",
    is_state: true,
    region: "West",
    has_coastline: false,
    highly_mountainous: false,
    shares_international_border: true,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Thar Desert, Palaces, Forts, Dal Baati",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: true,
    is_in_northeast: false,
    population_large: true,
    area_large: true,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: true,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: true,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Sikkim",
    is_state: true,
    region: "East",
    has_coastline: false,
    highly_mountainous: true,
    shares_international_border: true,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Kanchenjunga, Organic Farming, Monasteries",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: true,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: true,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: false,
    borders_china: true,
    borders_bangladesh: false,
    borders_nepal: true,
    borders_myanmar: false,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: false,
    smallest_by_area: true,
    known_for_classical_dance: false
  },
  {
    name: "Tamil Nadu",
    is_state: true,
    region: "South",
    has_coastline: true,
    highly_mountainous: true,
    shares_international_border: false,
    dominant_language_family: "Dravidian",
    high_literacy_85_plus: true,
    major_cultural_identifier: "Marina Beach, Idli Dosa, Temples, Pongal",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: true,
    area_large: true,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: true,
    known_for_beaches: true,
    known_for_spices: false,
    known_for_it_industry: true,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: true,
    smallest_by_area: false,
    known_for_classical_dance: true
  },
  {
    name: "Telangana",
    is_state: true,
    region: "South",
    has_coastline: false,
    highly_mountainous: false,
    shares_international_border: false,
    dominant_language_family: "Dravidian",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Charminar, Biryani, Kakatiya Architecture",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: true,
    formed_after_2000: true,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: true,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: true,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Tripura",
    is_state: true,
    region: "East",
    has_coastline: false,
    highly_mountainous: true,
    shares_international_border: true,
    dominant_language_family: "Sino-Tibetan",
    high_literacy_85_plus: true,
    major_cultural_identifier: "Unakoti Rock Carvings, Ujjayanta Palace",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: true,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: true,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: true,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: false,
    smallest_by_area: true,
    known_for_classical_dance: false
  },
  {
    name: "Uttar Pradesh",
    is_state: true,
    region: "North",
    has_coastline: false,
    highly_mountainous: false,
    shares_international_border: true,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Taj Mahal, Varanasi, Ganga, Ayodhya",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: true,
    area_large: true,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: true,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: true,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Uttarakhand",
    is_state: true,
    region: "North",
    has_coastline: false,
    highly_mountainous: true,
    shares_international_border: true,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Char Dham, Yoga Capital, Valley of Flowers",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: false,
    formed_after_2000: true,
    is_island_territory: false,
    hindi_speaking_majority: true,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: true,
    borders_bangladesh: false,
    borders_nepal: true,
    borders_myanmar: false,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "West Bengal",
    is_state: true,
    region: "East",
    has_coastline: true,
    highly_mountainous: true,
    shares_international_border: true,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Durga Puja, Rosogolla, Sundarbans, Darjeeling",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: true,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: true,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: true,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: true,
    borders_nepal: true,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: true,
    smallest_by_area: false,
    known_for_classical_dance: false
  },

  // ═══════════════════════════════════════
  //  UNION TERRITORIES (8)
  // ═══════════════════════════════════════

  {
    name: "Andaman and Nicobar Islands",
    is_state: false,
    region: "South",
    has_coastline: true,
    highly_mountainous: false,
    shares_international_border: false,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: true,
    major_cultural_identifier: "Cellular Jail, Radhanagar Beach, Islands",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: true,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: true,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Chandigarh",
    is_state: false,
    region: "North",
    has_coastline: false,
    highly_mountainous: false,
    shares_international_border: false,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: true,
    major_cultural_identifier: "Rock Garden, Sukhna Lake, Planned City",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: true,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: true,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: true,
    smallest_by_area: true,
    known_for_classical_dance: false
  },
  {
    name: "Dadra and Nagar Haveli and Daman and Diu",
    is_state: false,
    region: "West",
    has_coastline: true,
    highly_mountainous: false,
    shares_international_border: false,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Silvassa, Tribal Museum, Union Territory",
    historic_portuguese_influence: true,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: true,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: false,
    smallest_by_area: true,
    known_for_classical_dance: false
  },
  {
    name: "Delhi",
    is_state: false,
    region: "North",
    has_coastline: false,
    highly_mountainous: false,
    shares_international_border: false,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: true,
    major_cultural_identifier: "Red Fort, Qutub Minar, Capital, Street Food",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: true,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: true,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: true,
    smallest_by_area: true,
    known_for_classical_dance: false
  },
  {
    name: "Jammu and Kashmir",
    is_state: false,
    region: "North",
    has_coastline: false,
    highly_mountainous: true,
    shares_international_border: true,
    dominant_language_family: "Indo-Aryan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Dal Lake, Tulips, Shikara, Snow Mountains",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: false,
    formed_after_2000: true,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: true,
    known_for_it_industry: false,
    has_significant_tribal_population: false,
    borders_pakistan: true,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Ladakh",
    is_state: false,
    region: "North",
    has_coastline: false,
    highly_mountainous: true,
    shares_international_border: true,
    dominant_language_family: "Sino-Tibetan",
    high_literacy_85_plus: false,
    major_cultural_identifier: "Pangong Tso, Magnetic Hill, Cold Desert",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: true,
    is_in_northeast: false,
    population_large: false,
    area_large: false,
    formed_after_2000: true,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: false,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: true,
    borders_pakistan: true,
    borders_china: true,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: true,
    capital_is_major_metro: false,
    smallest_by_area: false,
    known_for_classical_dance: false
  },
  {
    name: "Lakshadweep",
    is_state: false,
    region: "South",
    has_coastline: true,
    highly_mountainous: false,
    shares_international_border: false,
    dominant_language_family: "Dravidian",
    high_literacy_85_plus: true,
    major_cultural_identifier: "Coral Reefs, Scuba Diving, Tiny Islands",
    historic_portuguese_influence: false,
    historic_french_influence: false,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: true,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: true,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: false,
    has_backwaters_or_lagoons: true,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: false,
    smallest_by_area: true,
    known_for_classical_dance: false
  },
  {
    name: "Puducherry",
    is_state: false,
    region: "South",
    has_coastline: true,
    highly_mountainous: false,
    shares_international_border: false,
    dominant_language_family: "Dravidian",
    high_literacy_85_plus: true,
    major_cultural_identifier: "French Quarter, Auroville, Promenade Beach",
    historic_portuguese_influence: false,
    historic_french_influence: true,
    famous_for_deserts: false,
    is_in_northeast: false,
    population_large: false,
    area_large: false,
    formed_after_2000: false,
    is_island_territory: false,
    hindi_speaking_majority: false,
    known_for_tea_coffee: false,
    known_for_beaches: true,
    known_for_spices: false,
    known_for_it_industry: false,
    has_significant_tribal_population: false,
    borders_pakistan: false,
    borders_china: false,
    borders_bangladesh: false,
    borders_nepal: false,
    borders_myanmar: false,
    known_for_historical_monuments: true,
    has_backwaters_or_lagoons: false,
    known_for_wildlife_sanctuaries: false,
    capital_is_major_metro: false,
    smallest_by_area: true,
    known_for_classical_dance: false
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { ANKANITOR_KNOWLEDGE_BASE };
}
